name: helium_validator
description: "A lightweight, powerful, and extensible validation library for Flutter."
version: 0.0.8
homepage: https://github.com/advait-bhitkar/helium_validator

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  intl: ^0.20.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
